# Generated by Django 3.2 on 2021-05-15 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Races',
            new_name='Race',
        ),
    ]
